In [1]:
import numpy as np

## Creating an Array

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
type(a)

numpy.ndarray

In [5]:
a + 10

array([11, 12, 13, 14, 15])

In [6]:
b = np.array( (1,2,3,4,5))

In [7]:
c = np.ones(5)

In [8]:
c

array([1., 1., 1., 1., 1.])

In [9]:
l1 = [1,2,3]
l2 = [10,20,30]
l1 + l2

[1, 2, 3, 10, 20, 30]

In [10]:
a + b 

array([ 2,  4,  6,  8, 10])

In [11]:
a + c

array([2., 3., 4., 5., 6.])

In [12]:
d = np.ones(4)

### Attributes of Array

In [42]:
a.shape

(5, 5)

In [ ]:
a.ndim

In [ ]:
a.size

In [ ]:
a.dtype

In [20]:
a = np.arange(1,1001)

#### Time difference between list and np array operations

In [23]:
%%timeit -n 10
a = np.arange(1,1001)
a2 = a + 10

The slowest run took 5.80 times longer than the fastest. This could mean that an intermediate result is being cached.
29.3 µs ± 24.8 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [25]:
%%timeit -n 10
l = [ n for n in range(1,1001)]
l2 = [ n + 10 for n in l ]

218 µs ± 19.4 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [31]:
dd = np.ones( (3,5), dtype=np.int32)

In [32]:
dd.dtype

dtype('int32')

#### Arrays with random numbers

In [34]:
a = np.random.randint(1,100,10)
a

array([71, 31,  8, 16, 91, 42, 88, 28, 80, 82])

In [37]:
a = np.random.rand(5,5)
a

array([[0.29377351, 0.66564589, 0.96541998, 0.62718671, 0.49611935],
       [0.44429875, 0.65225929, 0.56858597, 0.52996848, 0.11368892],
       [0.73396955, 0.27972546, 0.71549406, 0.25281362, 0.81252958],
       [0.5722915 , 0.48628903, 0.19767082, 0.37829461, 0.8392907 ],
       [0.38526575, 0.41769644, 0.23140979, 0.50590709, 0.27979324]])

In [41]:
la = np.linspace(1,10,4)
la

array([ 1.,  4.,  7., 10.])

### Indexing and slicing 

In [43]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
a[1], a[2:5], a [ [1,5,8]]

(2, array([3, 4, 5]), array([2, 6, 9]))

### Boolean indexing

In [49]:
b = np.random.randint(1,100,5)
b

array([39, 68, 50, 93, 65])

In [50]:
b[ [True,False, False, True, True]]

array([39, 93, 65])

In [52]:
a > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [53]:
a % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [54]:
marks = np.random.randint(0,100,10)
print("Actual marks ", marks)
print("Passed marks ", marks[ marks >= 50])

Actual marks  [38 31 26 59 40 96 18 12 14 76]
Passed marks  [59 96 76]


In [57]:
marks[-1]

76

In [58]:
marks[::-1]

array([76, 14, 12, 18, 96, 40, 59, 26, 31, 38])

In [59]:
marks[0:0:-1]

array([], dtype=int32)

In [60]:
dd = np.arange(1,10).reshape(3,3)
dd

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
dd[0,0]

1

In [63]:
dd[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])