In [1]:
import numpy as np

## Creating an Array

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
type(a)

numpy.ndarray

In [5]:
a + 10

array([11, 12, 13, 14, 15])

In [6]:
b = np.array( (1,2,3,4,5))

In [7]:
c = np.ones(5)

In [8]:
c

array([1., 1., 1., 1., 1.])

In [9]:
l1 = [1,2,3]
l2 = [10,20,30]
l1 + l2

[1, 2, 3, 10, 20, 30]

In [10]:
a + b 

array([ 2,  4,  6,  8, 10])

In [11]:
a + c

array([2., 3., 4., 5., 6.])

In [12]:
d = np.ones(4)

### Attributes of Array

In [13]:
a.shape

(5,)

In [14]:
a.ndim

1

In [15]:
a.size

5

In [16]:
a.dtype

dtype('int32')

In [17]:
a = np.arange(1,1001)

#### Time difference between list and np array operations

In [18]:
%%timeit -n 10
a = np.arange(1,1001)
a2 = a + 10

The slowest run took 4.23 times longer than the fastest. This could mean that an intermediate result is being cached.
10.6 µs ± 5.53 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [19]:
%%timeit -n 10
l = [ n for n in range(1,1001)]
l2 = [ n + 10 for n in l ]

102 µs ± 15.4 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [20]:
dd = np.ones( (3,5), dtype=np.int32)

In [21]:
dd.dtype

dtype('int32')

#### Arrays with random numbers

In [22]:
a = np.random.randint(1,100,10)
a

array([97, 16, 25, 53, 58, 68, 43, 59, 23, 68])

In [23]:
a = np.random.rand(5,5)
a

array([[0.69329897, 0.21464821, 0.98076605, 0.67723732, 0.1823471 ],
       [0.20807149, 0.61366325, 0.55888955, 0.9553049 , 0.46630217],
       [0.74426575, 0.94567373, 0.56064612, 0.25879717, 0.7385779 ],
       [0.0814111 , 0.21020044, 0.39994364, 0.79746496, 0.22163097],
       [0.9171388 , 0.53883511, 0.91930418, 0.03833762, 0.90680752]])

In [24]:
la = np.linspace(1,10,4)
la

array([ 1.,  4.,  7., 10.])

### Indexing and slicing 

In [25]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
a[1], a[2:5], a [ [1,5,8]]

(2, array([3, 4, 5]), array([2, 6, 9]))

### Boolean indexing

In [27]:
b = np.random.randint(1,100,5)
b

array([37,  2, 77, 89, 50])

In [28]:
b[ [True,False, False, True, True]]

array([37, 89, 50])

In [29]:
a > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [30]:
a % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [31]:
marks = np.random.randint(0,100,10)
print("Actual marks ", marks)
print("Passed marks ", marks[ marks >= 50])

Actual marks  [48 59 92 58 15 97  9  4 65 88]
Passed marks  [59 92 58 97 65 88]


In [32]:
marks[-1]

88

In [33]:
marks[::-1]

array([88, 65,  4,  9, 97, 15, 58, 92, 59, 48])

In [34]:
marks[0:0:-1]

array([], dtype=int32)

In [35]:
dd = np.arange(1,10).reshape(3,3)
dd

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
dd[0,0]

1

In [37]:
dd[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

#### Assignment on 2-Arp

In [44]:
v  = np.random.randint(1,100,100)
avg = v.mean()
v [ v > avg]

array([62, 53, 78, 66, 71, 59, 70, 59, 98, 65, 70, 60, 50, 93, 76, 61, 95,
       68, 93, 99, 80, 92, 51, 49, 51, 47, 52, 80, 58, 53, 55, 98, 97, 61,
       97, 86, 74, 57, 66, 71, 54, 68, 52, 68, 52, 60, 93, 91, 73, 77])

In [47]:
(v % 3 == 0).all()

False

In [48]:
np.all()

True

In [49]:
v.argmax()

40

In [50]:
v[40]

99

In [51]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
np.add(a,a)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [53]:
a + a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

#### Iterate array

In [54]:
for n in a:
     print(n)

1
2
3
4
5
6
7
8
9
10


In [55]:
marks = np.random.randint(0,100,20).reshape(5,4)
marks

array([[36, 56, 22, 24],
       [76, 94, 53, 18],
       [54, 87, 28, 93],
       [48, 84, 19, 90],
       [40, 21, 16, 71]])

In [57]:
for row in marks:
     print(row.sum(),row.mean(), row.max(), row.min())

138 34.5 56 22
241 60.25 94 18
262 65.5 93 28
241 60.25 90 19
148 37.0 71 16


In [59]:
(marks.flat > 50)

array([False,  True, False, False,  True,  True,  True, False,  True,
        True, False,  True, False,  True, False,  True, False, False,
       False,  True])

In [68]:
prices = np.random.randint(1,10,10)

In [62]:
prices.reshape(2,5)

array([[5, 3, 4, 1, 7],
       [6, 1, 9, 8, 9]])

In [63]:
prices

array([5, 3, 4, 1, 7, 6, 1, 9, 8, 9])

In [64]:
prices.reshape(2,-1)

array([[5, 3, 4, 1, 7],
       [6, 1, 9, 8, 9]])

In [69]:
prices.resize(3,5)

In [70]:
prices

array([[1, 3, 5, 9, 6],
       [6, 7, 9, 5, 3],
       [0, 0, 0, 0, 0]])

### Diff between view and copy

In [77]:
a = np.arange(1,11)

In [72]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
b = a[5:]
b

array([ 6,  7,  8,  9, 10])

In [79]:
b[0] = 0
b

array([ 0,  7,  8,  9, 10])

In [80]:
a

array([ 1,  2,  3,  4,  5,  0,  7,  8,  9, 10])

In [ ]:
np.hsplit