In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
type(a)

numpy.ndarray

In [6]:
a + 10

array([11, 12, 13, 14, 15])

In [7]:
b = np.array( (1,2,3,4,5))

In [8]:
c = np.ones(5)

In [9]:
c

array([1., 1., 1., 1., 1.])

In [10]:
l1 = [1,2,3]
l2 = [10,20,30]
l1 + l2

[1, 2, 3, 10, 20, 30]

In [11]:
a + b 

array([ 2,  4,  6,  8, 10])

In [12]:
a + c

array([2., 3., 4., 5., 6.])

In [13]:
d = np.ones(4)

In [14]:
a + d 

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

### Attributes of Array

In [15]:
a.shape

(5,)

In [16]:
a.ndim

1

In [17]:
a.size

5

In [18]:
a.dtype

dtype('int32')

In [21]:
a1 = np.arange(1,1001)